# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d42fc5c5457dfd6e5f15ad67cfaec90af39b47fa6fbbbd9e478e94de9ec46840b691e0d21d4ae912b16e172f154bbb933c48ca1c66e96c485cd5ff25db09c3d

test:
  secret_key_base: b9331e2866b908b1df880157622fb5aca6cd576a7e6e86f2faa830d3d3bf0c97bd396c4f14a391f23607d50cd04bf4ceffbdbb6db04c858e0991605303a0f8be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
