module ApplicationHelper
  def init_data
    @array_content = []
    @array_content.push ({"name" => "null", "title" => ""})
    @array_content.push ({"name" => "job_name","title" => "Job's name"})
    @array_content.push ({"name" => "company_name","title" => "Company's name"})
    @array_content.push ({"name" => "company_address","title" => "Company's address"})
    @array_content.push ({"name" => "staff_type","title" => "Staff's type"})
    @array_content.push ({"name" => "job_industry","title" => "Job's industry"})
    @array_content.push ({"name" => "job_type","title" => "Job's type"})
    @array_content.push ({"name" => "salary","title" => "Salary"})
    @array_content.push ({"name" => "work_place","title" => "Work's place(location)"})
    @array_content.push ({"name" => "job_content","title" => "Job's content"})
    @array_content.push ({"name" => "priority","title" => "Priority"})
    # @array_content.push ({"name" => "site_id","title" => "Site's ID"})
    @array_content.push ({"name" => "station","title" => "Station"})
    @array_content.push ({"name" => "station_id","title" => "Station's ID"})
    @array_content.push ({"name" => "job_category_id","title" => "Job category's ID"})
    @array_content.push ({"name" => "job_category","title" => "Job category"})
    @array_content.push ({"name" => "job_category_sub","title" => "Job category sub"})
    @array_content.push ({"name" => "job_category_full","title" => "Job category full"})
    @array_content.push ({"name" => "job_item_id","title" => "Job item's ID"})
    @array_content.push ({"name" => "job_no","title" => "Job's no"})
    @array_content.push ({"name" => "job_info_type","title" => "Job infomation's type"})
    @array_content.push ({"name" => "company_phoneno","title" => "Company's phone"})
    @array_content.push ({"name" => "company_faxno","title" => "Company's fax"})
    @array_content.push ({"name" => "company_description","title" => "Company's description"})
    @array_content.push ({"name" => "work_type","title" => "Work's type"})
    @array_content.push ({"name" => "work_period","title" => "Work's period"})
    @array_content.push ({"name" => "limit_age","title" => "Age limit"})
    @array_content.push ({"name" => "limit_age_reason","title" => "Age limit reason"})
    @array_content.push ({"name" => "work_hour","title" => "Work's hour"})
    @array_content.push ({"name" => "lunch_time","title" => "Lunch's time"})
    @array_content.push ({"name" => "overtime","title" => "Overtime"})
    @array_content.push ({"name" => "work_day_per_week","title" => "Work day per week"})
    @array_content.push ({"name" => "bonus","title" => "Bonus"})
    @array_content.push ({"name" => "day_off","title" => "Day off"})
    @array_content.push ({"name" => "two_days_off_per_week","title" => "Two days off per week"})
    @array_content.push ({"name" => "days_off_per_year","title" => "Days off per year"})
    @array_content.push ({"name" => "child_care_day_off","title" => "Child care day off"})
    @array_content.push ({"name" => "child_care_place","title" => "Child care's place"})
    # @array_content.push ({"name" => "work_place_change","title" => "Work place's change"})
    @array_content.push ({"name" => "company_staff_no","title" => "Company staff's no"})
    @array_content.push ({"name" => "insurances","title" => "Insurances"})
    @array_content.push ({"name" => "retirement","title" => "Retirement"})
    @array_content.push ({"name" => "re_apply_job","title" => "Re apply job"})
    @array_content.push ({"name" => "apply_living_place","title" => "Apply living place"})
    @array_content.push ({"name" => "commute_by_car","title" => "Commute by car"})
    @array_content.push ({"name" => "comute_support","title" => "Commute support"})
    @array_content.push ({"name" => "job_recruit_number","title" => "Job recruit's number"})
    @array_content.push ({"name" => "education_background","title" => "Education's background"})
    @array_content.push ({"name" => "required_experience","title" => "Required experience"})
    @array_content.push ({"name" => "required_certificate","title" => "Required certificate"})
    @array_content.push ({"name" => "extra_info","title" => "Extra's infomation"})
    @array_content.push ({"name" => "comments","title" => "Comments"})
    @array_content.push ({"name" => "registered_date","title" => "Registered's date"})
    @array_content.push ({"name" => "expiry_date","title" => "Expiry's date"})
    @array_content.push ({"name" => "contact_place","title" => "Contact's place"})
    @array_content.push ({"name" => "other_info","title" => "Other infomation"})
    @array_content.push ({"name" => "tencongty","title" => "Ten cong ty"})
    @array_content.push ({"name" => "sdt","title" => "phone number"})
    @array_content.push ({"name" => "email","title" => "Email"})
    @array_content.push ({"name" => "website","title" => "Website"})
    @array_content.push ({"name" => "address","title" => "Addess"})
    @array_content.push ({"name" => "status","title" => "Status"})
    @array_content.push ({"name" => "map_workplace","title" => "Map workplace"})
    @array_content.push ({"name" => "map_province","title" => "Map province"})
    @array_content.push ({"name" => "map_city","title" => "Map city"})
    @array_content.push ({"name" => "map_district","title" => "Map district"})
end
end
